### ISSUE TITLE
[BUG] App doesn't deploy when built with VS2022

### ISSUE THREAD

**Issue by DamienDoumer** [reactiveui/Akavache#738] opened 2021-11-24 20:24 UTC
When building an app that uses Akavache on Vs2019, everything works fine. But when moving the same app with no modification on VS 2022, I get a  `**System.MissingMethodException:** 'Method not found: int SQLitePCL.raw.sqlite3_bind_blob(SQLitePCL.sqlite3_stmt,int,System.ReadOnlySpan`1<byte>)'`
The app doesn't even run. No insertion or retrieval of data is done, it crashes at startup.  

**Steps To Reproduce**
Build and deploy an app using akavache  on Android using VS2022

**A project with reproduction of this Bug is found here. [AkavacheErr.git.zip](https://github.com/reactiveui/Akavache/files/7598539/AkavacheErr.git.zip)**

**Steps To Reproduce**
Build and deploy an app using akavache  on Android using VS2022

**Expected behavior**
Should build and deploy well on VS2022

**Environment**

- OS:       Android
- Device:  Any
- Version:   Any
- Working Version: None

**Comment by glennawatson** [comment] 2021-11-24 21:04
Duplicate of https://github.com/reactiveui/Akavache/issues/735

**Closed by glennawatson** 2021-11-24 21:04 UTC
Labels: Bug

**Comment by glennawatson** [comment] 2021-11-27 01:25
@ericsink There is a minimal repo on this issue.
