### ISSUE TITLE
[priority] feature: Support for tvOS 

### ISSUE THREAD

**Issue by amirvenus** [reactiveui/Akavache#681] opened 2021-06-06 01:36 UTC
I would like to ask for a support for TvOS. SQLitePCLRaw is already supporting this platform, so I think it will be probably straightforward to add this one also for Akavache.
When I tried to use already in my project, then I received an error:

'Failed to initialize Akavache properly. Do you have a reference to Akavache.dll?'

I have similar implementation for other platforms, and it is working fine.

P.S I am a contributor and I would be highly grateful if some priority is given to this Issue as it is a very burning and urgent requirement for my project. I tried adding the 'priority' label in the title; I hope I have done it right!

Thanks!

**Comment by glennawatson** [comment] 2021-06-06 01:41
Duplicate of https://github.com/reactiveui/Akavache/issues/540#issuecomment-855319155

**Closed by glennawatson** 2021-06-06 01:41 UTC
